"""empty message

Revision ID: a1b75fa131d2
Revises: 12301820a4bc
Create Date: 2021-03-09 09:41:28.193943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b75fa131d2'
down_revision = '12301820a4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Subscription', 'id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Subscription', sa.Column('id2', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
